### ISSUE TITLE
Empty Action classes after registration 

### ISSUE THREAD

**Issue by 0vulns** [apioo/fusio-adapter-util#2]
After I had register `Fusio\Adapter\Util\Adapter` the classes became an empty list

**Comment by 0vulns** [comment]
![screenshot from 2016-10-08 08-02-42](https://cloud.githubusercontent.com/assets/12600640/19208524/1a66e182-8cc9-11e6-9b12-fb69968e9bb5.png)

**Comment by chriskapp** [comment]
Hi, we have changed the way how actions are loaded so it is not possible to use 
theses adapters in the 0.3.x release. I will hopefully release the 0.4 version 
this weekend. That being said the util adapter contains only adapters like
conditione etc. which are already registered in the 0.3.x installation. You 
probably have to delete the registered classes from your fusio_action_class and
fusio_connection_class table.
